### PR TITLE
[WIP] Import cyclonus to network-policy-api repo 

### PR DESCRIPTION
**Pull request by astoycos**
This PR moves https://github.com/mattfenwick/cyclonus to this repo, with all the legacy commits and tags.

### CODE REVIEW

**Comment by mattfenwick** [comment]
What's next steps for this @astoycos ?

**Comment by astoycos** [comment]
So really there's nothing blocking this @mattfenwick , however I do think It would easier to let https://github.com/kubernetes-sigs/network-policy-api/pull/30 merge first to make sure we work around the directory structure/tools of the CRD since it's a bit more crucial we get that in.

**Comment by astoycos** [comment]
Close in favor of #39

**Pull request closed without merging**
