### PR TITLE
Add dyanngg to owners and security contacts

### PR DESCRIPTION
**Pull request by Dyanngg**
Signed-off-by: Yang Ding <dingyang@vmware.com>

### CODE REVIEW

**Comment by astoycos** [comment]
@abhiraut Or @rikatz Can you PTAL ?

**Comment by astoycos** [comment]
@Dyanngg Still some issues with the ORG here

**Comment by astoycos** [comment]
Did you ever figure this out @Dyanngg?

**Comment by Dyanngg** [comment]
> Did you ever figure this out @Dyanngg?

I‘m not sure why I'm still getting this error. I have gone through the sponsor process documented https://github.com/kubernetes/community/blob/master/community-membership.md#member and is already a member of k8s org

**Comment by astoycos** [comment]
So I think you need to also be a member or k8s-sigs possibly? https://github.com/orgs/kubernetes-sigs/people?query=dyanngg

**Pull request merged**
